# Generated by Django 5.2.9 on 2025-12-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=100)),
                ('total_budget', models.FloatField(default=0.0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_drafts', to='api.adminuser')),
            ],
            options={
                'unique_together': {('admin', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('date', models.CharField(max_length=20)),
                ('is_card', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.budgetdraft')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.adminuser')),
            ],
            options={
                'unique_together': {('admin', 'name')},
            },
        ),
    ]
